apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployEaristil
  labels:
    app: autodeployEaristil
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717630297201
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployEaristil
  template:
    metadata:
      labels:
        app: autodeployEaristil
    spec:
      containers:
        - name: autodeployEaristil
          image: acrworkflow1717630297201.azurecr.io/image-workflow-1717630297201:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
