apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy-earistil
  labels:
    app: autodeploy-earistil
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717632069763
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy-earistil
  template:
    metadata:
      labels:
        app: autodeploy-earistil
    spec:
      containers:
        - name: autodeploy-earistil
          image: acrworkflow1717630297201.azurecr.io/image-workflow-1717632069763:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
