apiVersion: v1
kind: Service
metadata:
  name: autodeploy-earistil
  namespace: namespace-workflow-1717632069763
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy-earistil
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000