apiVersion: v1
kind: Service
metadata:
  name: autodeployEaristil
  namespace: namespace-workflow-1717630297201
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployEaristil
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000